version: '3'

networks:
  internal-net:
    driver: bridge
    internal: true
  external-net:
    ipam:
      driver: bridge
      config:
        - subnet: "10.11.0.0/24"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    profiles: ["monitoring"]
    image: prom/prometheus:v2.30.0
    container_name: prometheus
    volumes:
      - /opt/moniotring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=500h' # 20 Days
      - '--web.enable-lifecycle'
      - '--web.external-url=/prometheus/'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - 127.0.0.1:9090:9090
    networks:
      - external-net
      - internal-net
    labels:
      group: "monitoring"

  grafana:
    profiles: ["monitoring"]
    image: grafana/grafana:8.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - /opt/moniotring/grafana:/etc/grafana/
      - /opt/moniotring/grafana/images/:/usr/share/grafana/public/img/
    env_file:
      - /opt/moniotring/grafana/config.grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - internal-net
      - external-net
    labels:
      group: "monitoring"

  nodeexporter:
    profiles: ["monitoring"]
    image: prom/node-exporter:v1.2.2
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    depends_on:
      - prometheus
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - internal-net
    labels:
      group: "monitoring"

  cadvisor:
    profiles: ["monitoring"]
    image: zcube/cadvisor:latest    # For ARM
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - prometheus
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - internal-net
    labels:
      group: "monitoring"

  ping:
    profiles: ["monitoring"]
    tty: true
    stdin_open: true
    expose:
      - 9115
    image: prom/blackbox-exporter
    restart: always
    volumes:
      - /opt/moniotring/blackbox:/config/
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - internal-net
      - external-net

  speedtest:
    profiles: ["monitoring"]
    expose:
      - 9798
    image: miguelndecarvalho/speedtest-exporter
    restart: always
    networks:
      - internal-net
      - external-net

  duckdns:
    image: lscr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europe/Berlin
      - SUBDOMAINS=mydomain
      - TOKEN=token
      - LOG_FILE=false #optional
    #    volumes:
    #      - /path/to/appdata/config:/config #optional
    restart: unless-stopped
    networks:
      - external-net

  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 127.0.0.1:8081:8080
    volumes:
      - /media/filebrowser:/data
      - /opt/filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
    networks:
      - internal-net

  vpn:
    image: ghcr.io/bubuntux/nordvpn
    hostname: nordvpn_at0m
    cap_add:
      - NET_ADMIN               # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=example_email     # Required
      - "PASS=passw0rd" # Required
      - CONNECT=United_States
      - CYBER_SEC=enable  
      - FIREWALL=enable
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.0/24,172.26.0.0/16  # So it can be accessed within the local network
    expose:
      - 8082  # Bittorent site
      - 8080  # Exporter
    networks:
      - internal-net
      - external-net
  
  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: service:vpn
    depends_on:
      - vpn  

  web:
    image: nginx:alpine
    volumes:
    - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
    - /opt/nginx/ssl:/etc/nginx/ssl
    ports:
    - "80:80"
    restart: unless-stopped
    networks:
      - internal-net

  homer:
    image: b4bz/homer:latest-amd64
    container_name: homer
    volumes:
      - /your/local/assets/:/www/assets
    environment:
    - UID=1000
    - GID=1000
    expose:
      - 8080
    restart: unless-stopped
    networks:
      - internal-net
