# Author: Veerendra Kakumanu
# Description: An Ansible playbook to necessary packages on my RPi4

- name: Init My RPi 4
  hosts: all
  gather_facts: yes
  vars_files:
    - pkg_vars.yml

  tasks:
    - name: Run Update
      apt:
        upgrade: true
        update_cache: yes
      ignore_errors: yes
      become: yes

    - name: Install Necessary Packges
      apt:
        name: "{{ pkgs }}"
        state: latest
        update_cache: yes
      become: yes

    - name: Install Python Packges
      pip:
        name: "{{ pip_pkgs }}"
      become: yes

    - name: Download tools/scripts
      get_url:
        url: "{{ item.value }}"
        dest: "/usr/local/bin/"
        mode: "0766"
      loop: "{{ lookup('dict', tools) }}"
      become: yes

    - name: Download nordvpn install script
      get_url:
        url: "{{ nordvpn_script }}"
        dest: "/tmp/install.sh"
        mode: "0766"

    - name: Install nordvpn
      shell: "/tmp/install.sh > /tmp/nordvpn-install.log"
      become: yes

    # Courtesy https://github.com/geerlingguy/ansible-role-docker_arm/blob/master/tasks/main.yml
    - name: Download Docker install convenience script.
      get_url:
        url: https://get.docker.com/
        dest: /tmp/get-docker.sh
        mode: 0775

    - name: Run Docker install convenience script.
      command: /tmp/get-docker.sh
      environment:
        CHANNEL: stable

    - name: Ensure Docker is started.
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker Compose using Pip.
      pip:
        name: docker-compose
        state: present
        executable: "pip3"

    - name: Ensure docker users are added to the docker group.
      user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: true
      become: yes

    - name: Run autoremove
      apt:
        autoremove: yes
      become: yes
