# Author: Veerendra Kakumanu
# Description: An Ansible playbook to necessary packages on my RPi4

- name: Init My RPi 4
  hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Run Update
      apt:
        upgrade: true
        update_cache: yes
      ignore_errors: yes
      become: yes

  post_tasks:
    - name: Run autoremove
      apt:
        autoremove: yes
      become: yes

  handlers:
    - name: Include handlers.
      import_tasks: tasks/handlers.yml

  tasks:
    #- name: Install Packages
    #  import_tasks: tasks/install-pkgs.yml

    - name: Setup Nginx Proxy
      import_tasks: tasks/nginx.yml

    #- name: Setup Docker
    #  import_tasks: tasks/docker.yml

    - name: Setup Monitoring
      import_tasks: tasks/monitoring.yml
