---
- name: Stop DuckDNS
  docker_compose:
    project_src: duckdns
    state: absent

- name: Run DuckDNS
  docker_compose:
    project_name: duckdns
    definition:
      version: "2.1"
      services:
        duckdns:
          image: lscr.io/linuxserver/duckdns
          container_name: duckdns
          environment:
            - PUID=1000 #optional
            - PGID=1000 #optional
            - TZ=Europe/Berlin
            - SUBDOMAINS=mydomain
            - TOKEN=token
            - LOG_FILE=false #optional
          #    volumes:
          #      - /path/to/appdata/config:/config #optional
          restart: unless-stopped
