---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu
  with_items:
    - /media/filebrowser
    - /opt/filebrowser/config

- name: Copy docker-compose.yaml
  copy:
    src: ./file-browser/docker-compose.yml
    dest: /opt/filebrowser/docker-compose.yml
    owner: ubuntu
    group: ubuntu

- name: docker-compose up
  docker_compose:
    project_src: "/opt/filebrowser/"
    build: false
