---
- name: Install Necessary Packges
  apt:
    name: "{{ pkgs }}"
    state: latest
    update_cache: yes
  become: true

- name: Install Snap Packages
  snap:
    name: "{{ snaps }}"
    classic: yes

- name: Install Python Packges
  pip:
    name: "{{ pip_pkgs }}"
  become: true

- name: Download tools/scripts
  get_url:
    url: "{{ item.value }}"
    dest: "/usr/local/bin/"
    mode: "0766"
  loop: "{{ lookup('dict', tools) }}"
  become: true

- name: Download dotfiles install script
  get_url:
    url: https://raw.githubusercontent.com/veerendra2/dotfiles/master/install.sh
    dest: /tmp/install-dotfiles.sh
    mode: 0775

- name: Run dotfiles install script
  command: /tmp/install-dotfiles.sh
# https://github.com/FideliusFalcon/Bettercap-Install-Raspberry-Pi-
#- name: Build bettercap
#  shell: |
#    export GOPATH=$HOME/go
#    export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
#    go get github.com/bettercap/bettercap
#    cd $GOPATH/src/github.com/bettercap/bettercap && make build && sudo make install
