---
- name: Install Necessary Packges
  apt:
    name: "{{ pkgs }}"
    state: latest
    update_cache: yes
  become: yes

- name: Install Python Packges
  pip:
    name: "{{ pip_pkgs }}"
  become: yes

- name: Download tools/scripts
  get_url:
    url: "{{ item.value }}"
    dest: "/usr/local/bin/"
    mode: "0766"
  loop: "{{ lookup('dict', tools) }}"
  become: yes

- name: Download nordvpn install script
  get_url:
    url: "{{ nordvpn_script }}"
    dest: "/tmp/install.sh"
    mode: "0766"

- name: Install nordvpn
  shell: "/tmp/install.sh > /tmp/nordvpn-install.log"
  become: yes

# https://github.com/FideliusFalcon/Bettercap-Install-Raspberry-Pi-
- name: Build bettercap
  shell: |
    export GOPATH=$HOME/go  
    export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
    go get github.com/bettercap/bettercap
    cd $GOPATH/src/github.com/bettercap/bettercap
    make build  
    sudo make install
