---
- name: Synchronize monitoring directory.
  synchronize:
    src: monitoring/
    dest: "/opt/monitoring/"
    delete: false
    recursive: true
    perms: false

- name: Ensure monitoring environment is running.
  docker_compose:
    project_src: "/opt/monitoring/"
    build: false
