---
- name: Synchronize monitoring directory.
  synchronize:
    src: nginx/
    dest: "/opt/nginx/"
    delete: false
    recursive: true
    perms: false

- name: Fetching ssl keys status
  stat:
    path: "{{ item }}"
  register: output
  with_items:
    - /opt/nginx/ssl/server.key
    - /opt/nginx/ssl/server.pem

- name: Generating self-signed certificates if required
  shell: |
    openssl req -x509 -nodes -subj '/CN=at0m' -days 365 \
    -newkey rsa:2048 -keyout /opt/nginx/ssl/server.key -out /opt/nginx/ssl/server.pem
  when: not output.results[0].stat.exists or not output.results[1].stat.exists

- name: Create networks
  docker_network:
    name: front-tier

- name: Run docker-compose up
  docker_compose:
    project_src: "/opt/nginx/"
    build: false
