version: '3'

networks:
  front-tier:
    external: true

services:
  filebrowser:
    image: hurlenko/filebrowser:v2.22.3
    user: "${UID}:${GID}"
    expose:
      - 8080
    volumes:
      - /media/filebrowser:/data
      - /opt/filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
    networks:
      - front-tier
