- name: Init My RPi 4
  hosts: all
  gather_facts: yes
  vars_files:
    - pkg_vars.yml

  tasks:
    - name: Create user 'mon'
      user:
        name: mon
        shell: /bin/false
        groups: docker
        create_home: no
        append: yes

    - name: Create prometheus and grafan directories
      file:
        path: "{{ item }}"
        state: directory
      with_list:
        - /opt/grafana
        - /opt/prometheus

    - name: Copy config files
      copy:
        src: "./monitoring/{{ item }}"
        dest: "/opt/{{ item }}"
      with_items:
        - prometheus/
        - grafana/

    - name: Copy docker-compose file
      copy:
        src: ./monitoring/docker-compose.yml
        dest: /opt/

    - name: Run docker-compose
      docker_compose:
        files: /opt/docker-compose.yml
